export const elements = {
  nextSongButton: document.getElementById("forwardButton"),
  previousSongButton: document.getElementById("backButton"),
  testElement: document.querySelector("#testElement"),
  currentTimeDisplay: document.getElementById("currentTime"),
  totalTimeDisplay: document.getElementById("totalTime"),
  fileInput: document.querySelector("#fileInput"),
  slider: document.querySelector("input[type='range']"),
  autoPlayButton: document.getElementById("autoPlayControl"),
  autoPlayIcon: document.getElementById("autoPlayIcon"),
  randomSongButton: document.getElementById("randomSongControl"),
  randomSongIcon: document.getElementById("randomSongIcon"),
  fileListContent: document.getElementById("fileListContent"),
  playerContainer: document.querySelector("#playerContainer"),
  currentSongCover: document.querySelector("#currentSong"),
  songTitle: document.querySelector("#songTitle"),
  artistName: document.querySelector("#artistName"),
  albumName: document.querySelector("#albumName"),
  dialogCloseButton: document.getElementById("dialogCloseButton"),
  fileListDialog: document.getElementById("fileListDialog"),
  fileListButton: document.querySelector('.dialog-button'),
  rewindButton: document.getElementById("rewindButton"),
  fastForwardButton: document.getElementById("fastForwardButton"),
  pausePlayButton: document.getElementById("stopButton")
};